# Generated by Django 3.1.2 on 2020-11-02 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressEN', models.CharField(max_length=200)),
                ('nameEN', models.CharField(max_length=200)),
                ('xCoor', models.DecimalField(decimal_places=8, max_digits=14)),
                ('yCoor', models.DecimalField(decimal_places=8, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=200)),
                ('lName', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('doc', models.DateField()),
                ('identity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cmName', models.CharField(max_length=200)),
                ('maxInfestPeriod', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('pkn', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('tov', models.CharField(max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotz.location')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotz.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='virus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotz.virus'),
        ),
    ]
